# GitHub Actions workflow name
name: Docker-Login-Build-Push
# event trigger(s)
on:
  # triggers on push to master branch
  push:
    branches: [master]
# variables used in this workflow
env:
  # variable holding my repo folder name (using DockerHub is assumed)
  DOCKER_HUB_REPO: project4
# jobs - each jobs runs on a runner - parralel by deafult, can be dependent based on id
#     https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobs
jobs:
  build_and_push:
    name: Build docker image and push to Docker Hub
    # OS of runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo to runner
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        # ID is used as a reference, from other jobs or steps
        #    using step ids: https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_HUB_REPO }}:latest
